### ISSUE TITLE
Is there plan to support mobile GPU?

### ISSUE THREAD

**Issue by llhe** [codeplaysoftware/computecpp-sdk#10]
Recently there is a trend to deploy DNN models on mobile phones, so offloading the computation to GPU can be a plus (although mobile GPU like Mali/Adreno/PowerVR have weak speedup compared to the desktop/server counterpart). Is there a plan to support such GPUs?

**Comment by rodburns** [comment]
We'd like to add support for mobile GPUs and are keen to work with mobile chip manufacturers to make this happen. If you are looking for support on specific hardware you can suggest that they work with us to make this happen.

**Comment by rodburns** [comment]
We have now released an ARM version of ComputeCpp so this is now possible however please note that in order to use ComputeCpp for ARM you will need the device drivers from the manufacturer of the hardware you are using. https://developer.codeplay.com/computecppce/latest/computecpp-ce-for-arm
