### ISSUE TITLE
Update Travis config (possibly move away from 14.04?)

### ISSUE THREAD

**Issue by DuncanMcBain** [codeplaysoftware/computecpp-sdk#100]
The Travis builds are becoming unstable on this older OS. Since we have a version of ComputeCpp that builds on 16.04, we should consider using that so that we don't have to add some other PPA to be able to get GCC 5.

It would also be nice if we only installed clang when building with clang, which would reduce the job time by a little.

**Comment by mehdi-goli** [comment]
Done

**Comment by DuncanMcBain** [comment]
The travis config has been updated to be much more lightweight and lets travis choose what to set in terms of compilers and so on. Fixed in #186 and #190
