### ISSUE TITLE
Filtering / masking OpenCL devices

### ISSUE THREAD

**Issue by lissyx** [codeplaysoftware/computecpp-sdk#107]
I could not find anything related to that in the documentation. One feature that CUDA has is the `CUDA_VISIBLE_DEVICES` environment variable, making it possible to mask / filter some devices when running code that relies on CUDA. How can this be achieved with ComputeCpp ? In my case, I have two cards on my system, one nvidia and one AMD, and I'd like to use only the AMD GPU for running OpenCL code.

**Comment by lissyx** [comment]
So basically we should handle that when we configure our TensorFlow session ? Like having a CLI arg flag we would pass to select the GPUs to use in the session ?

**Comment by DuncanMcBain** [comment]
It's on session creation - I believe just a string on the constructor, but I'm not sure.

**Comment by bill-95** [comment]
There is an OpenCL equivalent to CUDA_VISIBLE_DEVICES called GPU_DEVICE_ORDINAL, you can do:

> export GPU_DEVICE_ORDINAL=1

 to select the second device.

**Comment by lissyx** [comment]
Thanks @bill-95, this is somehting I search for a lot, but could never find.

**Comment by lissyx** [comment]
Why have I not closed this ?
