### ISSUE TITLE
Compiler crash when using ptx64 (ComputeCpp 0.7.0 / 0.8.0, Ubuntu / amd64)

### ISSUE THREAD

**Issue by lissyx** [codeplaysoftware/computecpp-sdk#108]
100% reproductible on my system (debian/sid uptodate) with those steps:
 - fetch current https://github.com/lukeiwanski/tensorflow/tree/integration/1.8, HEAD at https://github.com/lukeiwanski/tensorflow/commit/79966b699eff56c4577a5dcafbf264980554b783
 - configure with OpenCL/SYCL and ComputeCpp 0.7.0 (ubuntu 16.04 binaries)
 - build

**Comment by lissyx** [comment]
```
compute: note: diagnostic msg: PLEASE submit a bug report to sycl@codeplay.com and include the crash backtrace, preprocessed source, and associated run script.
compute: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
compute: note: diagnostic msg: /tmp/betainc_op-342619.cpp
compute: note: diagnostic msg: /tmp/betainc_op-3237e7.sycl
compute: note: diagnostic msg: /tmp/-d482fb.mdsycl
compute: note: diagnostic msg: /tmp/betainc_op-a88248.cpp
compute: note: diagnostic msg: /tmp/betainc_op-342619.sh
compute: note: diagnostic msg: 

********************
```

**Comment by lissyx** [comment]
[ccpp-crash.log](https://github.com/codeplaysoftware/computecpp-sdk/files/1974888/ccpp-crash.log)

**Comment by lissyx** [comment]
[ptx64-crash.zip](https://github.com/codeplaysoftware/computecpp-sdk/files/1974896/ptx64-crash.zip)

**Comment by DuncanMcBain** [comment]
Hi @lissyx,
Thanks for your report, I have passed it on to our internal compiler team who will take a look.
Duncan.

**Comment by lissyx** [comment]
Giving a spin to 0.8.0, I'm hitting a typo issue:
```
fatal error: cannot open file 'DeepSpeech/ComputeCpp-CE-0.8.0-Ubuntu-16.04-x86_64/lib/ComputeCppTargets/nvptx64--nvidiacl.bc': No such file or directory
```

What exists, though, is:
```
-rw-r--r-- 1 alexandre alexandre 13M mai    5 23:24 DeepSpeech/ComputeCpp-CE-0.8.0-Ubuntu-16.04-x86_64/lib/ComputeCppTargts/nvptx64--nvidiacl.bc
```

See the missing `e` in `ComputeCppTargts` :)

**Comment by DuncanMcBain** [comment]
Huh, sounds like we need more testing! What happens if you move the file to the correct location - same crash?

**Comment by lissyx** [comment]
Yes, same crash as reported initially with the typo fixed, I've updated the title accordingly :(

**Comment by DuncanMcBain** [comment]
OK, thanks. The team is also aware of the typo, thanks for that!

**Comment by DuncanMcBain** [comment]
Hi @lissyx,
We have managed to reproduce this error internally and hopefully have a fix for it, once it gets through our testing. Thanks for bringing this to our attention!

**Comment by rodburns** [comment]
This issue has been resolved. Please re-open this issue if you find any further related problems.

**Comment by lissyx** [comment]
@DuncanMcBain Hello, I was about to check if we could have more luck with current TensorFlow master / r1.11 with OpenCL and maybe `NVIDIA` hardware, but I don't see new code on TensorFlow upstream repository for OpenCL, and @lukeiwanski repo seems to be stuck to r1.8. I couldn't find any doc / references uptodate, is this work still going on r1.8 or am I missing something ?

**Comment by lissyx** [comment]
@Rbiessy Oh that's nice! Any hope / ETA to get r1.11 soonish ? We moved directly there :).

**Comment by Rbiessy** [comment]
That is not planned no :/
We are waiting to see what the future releases look like. From what I've read the last 1.x release will be either 1.12 or 1.13 before 2.0 goes out so we may wait for the last 1.x to pull from upstream again.
