### ISSUE TITLE
Zero-size SYCLMalloc returns non-unique addresses

### ISSUE THREAD

**Issue by r-potter** [codeplaysoftware/computecpp-sdk#109]
Calling SYCLMalloc with size zero returns a non-null, non-unique address.

```
auto a = SYCLMalloc(0, pMap);
auto b = SYCLMalloc(0, pMap);
auto c = SYCLMalloc(0, pMap);
```

This will currently set a,b,c == 0x1000. If zero size mallocs are allowed (which I believe is required for Eigen compatibility), then SYCLMalloc should return unique virtual addresses.

**Comment by Ruyk** [comment]
What would be the expected behaviour? According to the [POSIX and C](http://pubs.opengroup.org/onlinepubs/9699919799/) standards, malloc of size 0 behavior:
```
 If the size of the space requested is 0, the behavior is implementation-defined: either a null pointer shall be returned, or the behavior shall be as if the size were some non-zero value, except that the behavior is undefined if the returned pointer is used to access an object
```
Which is technically what is happening. I am happy to return a nullptr if that makes detecting errors easier...

**Comment by DuncanMcBain** [comment]
I believe either one of TensorFlow or Eigen relies on size-zero allocations being allowed. In that case, a `nullptr` would be a problem. However, I think the current behaviour isn't consistent with the second bullet point - shouldn't malloc return unique pointers? Moreover, this means that the PointerMapper will misbehave (what happens when you try to free once, or three times?)

**Comment by r-potter** [comment]
I agree with @DuncanMcBain . Either null or the equivalent of a non-zero allocation would be fine (although I believe there is some Eigen or Tensorflow requirement that prefers non-null). What's problematic is returning the same non-null address. There is actually a much more problematic case:

  auto a = SYCLMalloc(0, pMap); // Returns 0x1000
  auto b = SYCLMalloc(4096, pMap); // Returns 0x1000 + 0
  if (a) {
    SYCLFree(a, pMap); // b gets accidentally freed because it shares an address.
  }

**Comment by Ruyk** [comment]
That makes sense to me. I didn't realize at first about the potential double free issue.

Thanks for the pull request from @Rbiessy, this is sorted out now. If you are happy with the solution I think we can close it.

**Comment by r-potter** [comment]
LGTM

**Comment by DuncanMcBain** [comment]
Thanks, all!
