### ISSUE TITLE
Return an error when ComputeCpp_INFO_EXECUTABLE cannot be found

### ISSUE THREAD

**Issue by alistairlow** [codeplaysoftware/computecpp-sdk#126]
Running with ComputeCpp 0.9.0 on 32-bit ARM. If the computecpp_info binary cannot be found, the command silently succeeds, but ${ComputeCpp_INFO_EXECUTABLE} "--dump-version" fails. It would be easier to debug if the initial error was reported.

**Comment by DuncanMcBain** [comment]
Fixed by #161
