### ISSUE TITLE
Confusing output in parallel_for example

### ISSUE THREAD

**Issue by mcopik** [codeplaysoftware/computecpp-sdk#13]
Parallel_for prints in the end that results are correct even if all of them are incorrect:
https://github.com/codeplaysoftware/computecpp-sdk/blob/master/samples/parallel_for/parallel_for.cpp#L103

The sample should terminate after finding an incorrect result or a boolean flag should be used to not display this message.

**Comment by DuncanMcBain** [comment]
Hi Marcin, thanks for the fix. If you accept the CLA we can get it merged.

**Comment by mcopik** [comment]
Signed.
