### ISSUE TITLE
Adding an alternate SYCL example for CUDA example

### ISSUE THREAD

**Issue by keryell** [codeplaysoftware/computecpp-sdk#134]
https://developer.codeplay.com/computecppce/latest/computecpp-for-cuda-developers gives a nice comparison of a CUDA program in a SYCL syntax with the same code organization.
But it would be also interesting to add another version of the code with a more SYCL-natural syntax at the end of the article, using a lambda instead of a separate function for the kernel computational part.
The code should be terser then.

To be added to https://github.com/codeplaysoftware/computecpp-sdk/tree/master/utils/cuda_to_sycl

**Comment by rodburns** [comment]
Good idea.

**Comment by rodburns** [comment]
A whole new section with sample code has been added to our documentation. https://developer.codeplay.com/computecppce/latest/sycl-for-cuda-developers
