### ISSUE TITLE
CMake / Cinder / ci_make_app

### ISSUE THREAD

**Issue by pkestene** [codeplaysoftware/computecpp-sdk#136]
Hello,

While trying to build the demos app, it actually fails at the cmake configuring step because the two macros: `ci_make_app` and `add_sycl_to_target` are both using `target_link_libraries` macro but:

- add_sycl_to_target explicitly use target_link_libraries with PUBLIC keyword
- ci_make_app doesn't use any keyword

so cmake configure complains with 
> All uses of target_link_libraries with a target must be either all-keyword or all-plain.

I guess Cinder should modify its `ci_make_app` macro to explicitly state the link interface.
Let me add that if I modify `ci_make_app` this way, the demos build and run fine.

Am I missing someting about building the demos ? Is the modification really needed or avoidable ?

**Comment by mmha** [comment]
Hey,

Thanks for reporting. I created a patch for `FindComputeCpp.cmake` to support the legacy syntax by using `set_property` instead. The graphical demos should compile now.

While we as a library vendor should do this to avoid breaking user code, it'd like to stress that this is a legacy feature of CMake from the days where target property progagation did not distinguish between build and usage requirements and shouldn't be used anymore unless you have to maintain legacy code. 

I think we should also create an issue/PR at Cinder to either switch to keyword `target_link_libraries()` or use `set_property()` instead.

**Comment by pkestene** [comment]
Thanks.
I agree that Cinder should switch to explicit keyword in their target_link_libraries.

**Comment by DuncanMcBain** [comment]
This was closed by the MR, but let us know if 1) it works 2) you run into any other issues! Not many folks externally have tried the demos!
