### ISSUE TITLE
CMake script supporting multiple translation units 

### ISSUE THREAD

**Issue by mcopik** [codeplaysoftware/computecpp-sdk#15]
The current version of [`add_sycl_to_target`](https://github.com/mcopik/computecpp-sdk/blob/master/cmake/Modules/FindComputeCpp.cmake#L238) supports only targets with one source file. It is a non-negligible limitation, many C++ applications or libraries consist of multiple translation units. Is there a technical reason behind this limitation?

In my fork I implemented [a single extension](https://github.com/mcopik/computecpp-sdk/blob/cmake_multiple_sources/cmake/Modules/FindComputeCpp.cmake#L246) creating multiple custom targets for each source file. I'm using an additional counter to distinguish between targets created for source files with the same name; it may happen for files located in different directories.
A [modified example](https://github.com/mcopik/computecpp-sdk/tree/cmake_multiple_sources_example/samples/example_sycl_application) proves that an application with SYCL kernels in two source files builds correctly; I can't verify if it executes correctly though, due to problems with SYCL runtime, but I do not expect any problems here.

I can open a pull request, as long as you don't see a problem with this approach and you are interested in it.

**Comment by DuncanMcBain** [comment]
Hi Marcin, that sounds interesting! We'd definitely be interested in merging this if you are happy to share it. I've had a quick look and everything seems fine, so if you make a merge request I'm sure we'll be able to accept it quickly.

**Comment by mcopik** [comment]
I opened a pull request.

**Comment by DuncanMcBain** [comment]
Brilliant, thank you very much!
