### ISSUE TITLE
Reliable way to remove Computecpp:CC0027 on memcpy/memset intrinsics

### ISSUE THREAD

**Issue by MathiasMagnus** [codeplaysoftware/computecpp-sdk#155]
I would like to add a test during CMake configuration time, whether it is safe to omit disabling the llvm intrinsics for the aforementioned functions. In nature it would be similar to what I recently added for #149, namely compiling a small test program that would execute for all platforms and devices on the compiling machine and only disable the intrinsics if any of them fail on the test.

I believe that in the vast majority of the cases, the compiling machine will also be the one to execute, so this configure-time check might even be made the default. Seeing compiler warnings which originate from deep internal machinery and the user having no means of testing their validity is not good UX.

If someone gave a code snippet that is able to test this capability of the executing runtime for a given device, I'd craft the surrounding code.

My guess is that this would be placed behind a `COMPUTECPP_PORTABLE_BUILD` cache variable, and the Codeplay folks could decide on a default value. I'd argue that `OFF` is the right choice. The vast majority of builds is non-release in the sense that portable builds, where it is not known what the execution environment is, when one is creating installers or builds that will be offloaded to clusters (and also not be built there).

**Comment by MathiasMagnus** [comment]
Could I get a response to this issue? I spent a few minutes trying to silence this thing, but I can't seem to find a way to turn of SYCL-specific warnings.

I figured my AMD runtime does need this serialization, and I am aware of it, so I just want to use this feature and not see the warning on every build. I would gladly cook up automatic detection for this in the CMake scripts, just please tell me, how can I control this warning and how can I test if it's needed or not?

**Comment by DuncanMcBain** [comment]
Hi @MathiasMagnus,
Thanks for pinging us on this issue, we actually have updated our advice for this flag. We would recommend turning on -no-serial-memop unconditionally, as we have likely fixed the underlying problems that necessitated the flag in the first place. It is likely that we will change the flag in the future so that -no-serial-memop is the default, with a new flag (-serial-memop) for the old behaviour. If and when we do this, it will be mentioned in the release notes.

Best,
Duncan.
