### ISSUE TITLE
Is it possible for ComputeCpp to compile *.cu to SYCL binary?

### ISSUE THREAD

**Issue by ghostplant** [codeplaysoftware/computecpp-sdk#173]
```sh
__device__ void vector_add(int *z, int *x, int *y) {
  ..
}

int main() {
  ...
  vector_add<<<2, 2>>>(z, x, y);
}
```

Just like the sample cuda source code above, it is possible to use `computecpp` command to compile the code into SYCL binary that could execute over OpenCL driver?

**Comment by DuncanMcBain** [comment]
Hi @ghostplant, the compiler that ships with ComputeCpp cannot compile CUDA device code. The HIP project from AMD is probably the closest thing to what you're looking for. https://github.com/ROCm-Developer-Tools/HIP

**Comment by ghostplant** [comment]
@DuncanMcBain Thank you. I need a compiler that can compile those codes into other kinds of OpenCL 1.2 devices, while HIP is officially said not supporting generic OpenCL devices except for some AMD GPUs. Do you have more suggestions?

**Comment by DuncanMcBain** [comment]
There seem to be a couple of options from Googling around, but I don't know of any specifics, sorry. Though now that I think about it, we do offer a [guide and code](https://github.com/codeplaysoftware/computecpp-sdk/tree/master/utils/cuda_to_sycl/converter) in this repository. I'm not sure how I forgot about that... Maybe this would work for your purposes? It's not totally automatic, but it saves a lot of the work.

**Comment by ghostplant** [comment]
@DuncanMcBain Seems nice. Would be many *.cu cases failed to convert automatically and what about future enhancement plans?

**Comment by DuncanMcBain** [comment]
I don't believe we have any further work planned on it. I also don't think many people have used it, so I'm not sure how automatic the process is. I imagine if you're using built-in functions it will need more manual work but I have no hard information.

**Comment by DuncanMcBain** [comment]
Our PTX backend is not yet fully-featured, so there are certainly lots of things that won't work. FWIW though only 4 of our samples in this repo fail when I run them using PTX locally, and two of those are because we don't support images in the ptx backend.

**Comment by ghostplant** [comment]
OK. Do you have a brief list to explain what kinds of bitcode is fully-featured by computecpp and respective OpenCL hardward could support them well?

**Comment by DuncanMcBain** [comment]
Our SPIR and SPIR-V output should be considered fully functional. Most devices accept SPIR, but there are a few that don't. I think you'd be better off referring to their documentation for whether they support SPIR or not, but roughly NVIDIA only takes PTX, and Intel's Compute Runtime accepts SPIR-V as well as SPIR. For everything else, SPIR is a good starting point.

**Comment by ghostplant** [comment]
@DuncanMcBain Great, I'll focus on some SPIR(-V) environments. Thank you very much!
