### ISSUE TITLE
nvidia ptx64, hello-world throws: terminate called after throwing an instance of 'cl::sycl::compile_program_error'

### ISSUE THREAD

**Issue by KestutisMa** [codeplaysoftware/computecpp-sdk#191]
Did as described here https://developer.codeplay.com/products/computecpp/ce/guides/platform-support/targeting-nvidia-ptx?
```
[kest@archlinux hello-world]$ ./hello-world 
Running on GeForce GTX 960
terminate called after throwing an instance of 'cl::sycl::compile_program_error'
Aborted (core dumped)
[kest@archlinux hello-world]$

**Comment by DuncanMcBain** [comment]
Have you definitely set your bitcode type to ptx? If you run something like parallel-for, you should get much better error output (hello world doesn't have a lot of error handling, parallel-for does).

**Comment by KestutisMa** [comment]
Thanks! it really was a problem with build script that ptx64 was not passing to generation of final executable. Using parallel-for build script example I managed to compile and run successfully.
