### ISSUE TITLE
how to pass parameters by value to kernel?

### ISSUE THREAD

**Issue by KestutisMa** [codeplaysoftware/computecpp-sdk#192]
How to to pass struct, int or other type parameters by value to kernel?
Is it possible only by creating buffers?

CUDA call of "kernel_1" equivalent would be `kernel_1<<<grid, block>>>(dev_n, dev_m, dev_h, dev_I, dev_V_YX, i, i_reg, dt_sim, cellCountX, cellCountY);` where "dev_n, dev_m, dev_h, dev_I, dev_V_YX" are device pointers, and "i, i_reg, dt_sim, cellCountX, cellCountY)" are variables passed by values.

**Comment by mmha** [comment]
Hello @KestutisMa,

With SYCL your kernels are not free functions like in CUDA, but function objects. The function object's member variables are your kernel arguments.

Your declaration would roughly translate to this code below.

```c++
struct some_kernel_arg {
  float a;
  int b;
};

struct kernel_1 {
    cl::sycl::accessor<float, 2,
        cl::sycl::access::mode::read_write,
        cl::sycl::access::target::global_buffer> dev_n, dev_m, dev_h, dev_I, dev_V_YX;
    int i, i_reg, dt_sim, cellCountX, cellCountY;
    some_kernel_arg arg;

    void operator()(cl::sycl::nd_item<2> idx) const {

    }
};

extern cl::sycl::range<2> grid, block;

int main() {
    cl::sycl::queue q;
    q.submit([](cl::sycl::handler &h) {
        cl::sycl::nd_range<2> range{grid, block};
        kernel_1 k{ /* ... */};
        h.parallel_for(range, k);
    });
}
```

To reduce verbosity you can also use lambdas and their capture list:

```c++
struct kernel_1;

int main() {
    cl::sycl::queue q;
    q.submit([](cl::sycl::handler &h) {
        cl::sycl::nd_range<2> range{grid, block};
        cl::sycl::accessor<float, 2,
            cl::sycl::access::mode::read_write,
            cl::sycl::access::target::global_buffer>
        dev_n{ ... }, dev_m{ ... }, dev_h{ ... }, dev_I{ ... }, dev_V_YX{ ... };

        int i, i_reg, dt_sim, cellCountX, cellCountY;
        
        h.parallel_for<kernel_1>(range, [=](cl::sycl::nd_item<2> idx) {
//                                       ^-- Note the copy
            auto gid = idx.get_global_id();
            float x = dev_n[gid];
        });
    });
}
```

In C++14 and later you can use generalized lambda captures to further decrease verbosity:

```c++
h.parallel_for<kernel_1>(range, [
    dev_n = nbuf.get_access(...),
    i = 42,
    // ...
  ](cl::sycl::nd_item<2> idx) {

});
```

Let me know if that helps :)

**Comment by KestutisMa** [comment]
Thank you, Morris, for detailed answer. I will try this.
