### ISSUE TITLE
Hip/rocm  support on Windows

### ISSUE THREAD

**Issue by PontiacGTX** [codeplaysoftware/computecpp-sdk#204]
Since AMD dropped SPIRV driver support and currently they use hip/rocm and there isnt a solution for developing on windows aside using the old drivers it wouldnt allow to support newer gpus  and develop in windows if computecpp had hip/rocm backend?  maybe porting a project like  https://github.com/illuhad/hipSYCL to windows would allow to support new devices(like navi) and keep the support for windows for amd gpus

**Comment by rodburns** [comment]
Hi, I'm not sure I understand this issue. If you are asking the hipSCYL project to provide Windows support I would suggest raising that as an issue on that project. There has been some previous discussion on the topic [here](https://stackoverflow.com/questions/56222153/hipsycl-for-windows/56235123?noredirect=1#comment99100084_56235123)

**Comment by PontiacGTX** [comment]
Currently the only way to use computecpp is using an outdated driver since last time AMD supported SPIR on their drivers was around  2017  and the only possible way to use compute cpp is using these outdated drivers which will not work on future gpus (i.e Navi) or those who wouldnt want to use old drivers

https://community.amd.com/thread/232093

so if computecpp used ROCm at the back on windows for amd would allow to develop with newer drivers or future gpus, AMD has mentioned something regarding  bringing back the spir support (which seems it required on computecpp because gemerated errors like this)
https://support.codeplay.com/t/error-when-compiling-sample/183

**Comment by MathiasMagnus** [comment]
@PontiacGTX There is only one issue with your request: there is no ROCm on Windows. AMD hasn't delivered a HIP runtime yet for the Windows platform. If they would, you'd have hipSYCL support on the same day.

**Comment by mcleary** [comment]
As @MathiasMagnus pointed out, there is no ROCm on Windows.
