### ISSUE TITLE
OpenCL Library

### ISSUE THREAD

**Issue by mongrelgem** [codeplaysoftware/computecpp-sdk#208]
How do I point the build to use a particular version of CL headers and libraries ? I tried altering the variables OpenCL_LIBRARIES and OpenCL_INCLUDE_DIRS when building in cmake but when it is building the samples , it reverts to using the default libOpenCL.so from the system 

Thanks

**Comment by mcleary** [comment]
It seems that you are actually building the SDK using your particular OpenCL, however, when running, the executable will prefer the system installation. You can check this with the `ldd` command. It will give you the path of the OpenCL that will be loaded.

To change you can point the environment variable `LD_LIBRARY_PATH` to the folder where your `libOpenCL.so` is. After exporting this variable run `ldd` again and you should see the path to your OpenCL.

**Comment by mongrelgem** [comment]
Well , that is sort of the problem. 
[ 14%] Linking CXX executable opencl-c-interop
cd /scratch/SYCL/computecpp-sdk/build/samples && /usr/bin/cmake -E cmake_link_script CMakeFiles/opencl-c-interop.dir/link.txt --verbose=1
/usr/bin/c++    -Wall   CMakeFiles/opencl-c-interop.dir/opencl-c-interop.cpp.o  -o opencl-c-interop /scratch/SYCL/computecpp/lib/libComputeCpp.so /scratch/AMD/cl-runtime/dbg64b/libOpenCL.a -Wl,-rpath,/scratch/SYCL/computecpp/lib: 
/usr/bin/ld: CMakeFiles/opencl-c-interop.dir/opencl-c-interop.cpp.o: undefined reference to symbol 'clReleaseDevice@@OPENCL_1.2'
//usr/lib/x86_64-linux-gnu/libOpenCL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
samples/CMakeFiles/opencl-c-interop.dir/build.make:99: recipe for target 'samples/opencl-c-interop' failed

My executable doesn't compile because of this error. Could this be because I am using an emulated runtime and static OpenCL library when building. Is there an option to build the executables as static ?

**Comment by DuncanMcBain** [comment]
So I did a little trial earlier and I *think* you'll be OK with this setup - as far as I can tell, it will end up using the static symbols for everything, even without the OpenCL shared library.

As for the error there, this is slightly embarrassing, you can simply delete [line 183](../blob/master/samples/opencl-c-interop.cpp#L183) from the opencl-c-interop sample. `clReleaseDevice` is only meaningful for OpenCL subdevices, and so removing that line is not a problem.

For what it's worth, I've never seen a static OpenCL library. ComputeCpp as a library has ` DT_NEEDED` of `libOpenCL.so` but my testing indicates that if a symbol is already satisfied by statically-linked code, it Just Works (tm). Let us know how you get on!

**Comment by mongrelgem** [comment]
@DuncanMcBain  Thanks for that. Yeah that solved my compilation problem. It seems to compile the program properly. I faced another cl::sycl::compile_program_error , however that is another issue in itself. Browsing through the forum , I realize it is mainly due to lack of SPIR support which is needed. Anyway thanks for your help.

**Comment by DuncanMcBain** [comment]
`compute++` can output different forms of IR, but I'm guessing this static OpenCL only supports OpenCL C? What is it you're trying to do? The sample you're looking at has both an OpenCL C kernel and a SPIR kernel, the former should work just fine (you'd need to remove the latter). More generally though, yes, SPIR support is required.

**Comment by rodburns** [comment]
I'm going to close this as it seems to be resolved. Please re-open it if you want any more clarification.
