### ISSUE TITLE
OpenCL Code 

### ISSUE THREAD

**Issue by mongrelgem** [codeplaysoftware/computecpp-sdk#209]
I was just wondering if it possible to spit out the OpenCL Code or API calls that sycl is converted to. In essence , SYCL is a template layer sitting on top on OpenCL and their webpage says that all sycl templates ultimately boils down to OpenCL API calls. Is there any way to use the toolchain to actually look at the openCL code which is finally executed on the device say for the simple_vector_add program ?

Cheers

**Comment by rodburns** [comment]
Please see the response to your original issue on our support forums. https://support.codeplay.com/t/sycl-to-opencl-code/261/2 
Thanks.
