### ISSUE TITLE
Unknown CMake command "ci_make_app"

### ISSUE THREAD

**Issue by SlavMFM** [codeplaysoftware/computecpp-sdk#223]
Running `cmake ./` at **demos/mandelbrot** gives 
> CMake Error at CMakeLists.txt:7 (ci_make_app):
  Unknown CMake command "ci_make_app".

error.
My system is Ubuntu 18.04.04, cmake 3.10.2.

**Comment by DuncanMcBain** [comment]
Hi @SlavMFM, you've closed this issue, did you manage to fix it? At a guess you should be generating based on the `CMakeLists.txt` in the `demos` directory, not `demos/mandelbrot`.

**Comment by SlavMFM** [comment]
Hello! Yeah, it was exactly the problem! Had to just **cd ../** several times, silly me, sorry. Spent ~10 hours and all sanity beforehand trying to set up OpenCL libs/headers for my AMD gpu ^^

**Comment by DuncanMcBain** [comment]
Ouch, well I'm glad it seems to be working now! Please let us know if you run into any other issues with the demos, I don't try them often but generally expect that they should work (equally if there are steps missing from the readmes, I'll be happy to update them).
