### ISSUE TITLE
computecpp-sdk/samples/custom-device-selector.cpp checks for "cl_khr_spir" extension only

### ISSUE THREAD

**Issue by garimagu** [codeplaysoftware/computecpp-sdk#227]
Hi, the test case computecpp-sdk/samples/custom-device-selector.cpp is only checking for support for cl_khr_spir, if a device supports SPIRV, it will return cl_khr_il_program.
Is this sample not meant for such platforms that support SPIR-V?

**Comment by mcleary** [comment]
That is a fair point but in my point of view this sample is meant to show you how to write a custom device selector. In the case of the sample, the selector is meant to select only devices supporting SPIR, but you can quickly adapt it to your needs.

**Comment by DuncanMcBain** [comment]
Hi @garimagu, what would be a good resolution here for you? Do you run this as a test or similar?

**Comment by garimagu** [comment]
Hi Duncan, I run this as a test with intel/llvm sycl compiler.
As per me the code can check for extension cl_khr_spir || cl_khr_il_program and check the intermediate language supported using CL_DEVICE_IL_VERSION_KHR.
But I understand that this is a sample. 
I will close this issue for now.
Thank you.

**Comment by garimagu** [comment]
Hi, 

I run this as a test with intel/llvm compiler and see my compiler/platform failing this test.
As a fix, there are multiple options, please see if it possible to fix the code for this change.

1. Return a low positive value in custom_selector for host.
SYCL spec says that the host device should always be available.
Recommended change:
    ...
    }
    if (device.get_info<info::device::device_type>() ==
          info::device_type::host) {
        return 25;
    }
    /* Devices with a negative score will never be chosen. */
    return -1;
  }

2. Check for SPIR or SPIRV. 
Recommended Change:
...
if (device.has_extension(cl::sycl::string_class("cl_khr_spir")) || 
device.has_extension(cl::sycl::string_class("cl_khr_il_program"))) {
...

3. Use try-catch to catch the synchronous exception. When no device is found, it should throw a message and gracefully exit the test.
Change will look something like:
try {
    queue MyQueue ... 
    // kernel...
 } catch (cl::sycl::exception const &e) {
    std::cout << "Caught synchronous SYCL exception:\n"
              << e.what() << std::endl;
    if (e.get_cl_code() == CL_DEVICE_NOT_FOUND)  {
        std::cout<< "No supported device found." << std::endl;
        return 0;
    }
 }

**Comment by DuncanMcBain** [comment]
Hi @garimagu, if you're happy with the fix in #232 (which looks like solution number two) then I'm happy to commit it.

**Comment by garimagu** [comment]
> Hi @garimagu, if you're happy with the fix in #232 (which looks like solution number two) then I'm happy to commit it.

Thank you @DuncanMcBain
