### ISSUE TITLE
Using compute++ with compiler different from /usr/bin/c++

### ISSUE THREAD

**Issue by benvanwerkhoven** [codeplaysoftware/computecpp-sdk#237]
I'm working on a cluster computer with many different compiler installations available through a module system. In my experience this is how most HPC systems work. Unfortunately, /usr/bin/c++ is very old (GCC 4.8.5), and since I'm not a system administrator I cannot change this.

I've been trying to get any bit of SYCL code to compile for hours now without any success. Because everything is wrapped CMake, it is hard for me to figure out what is going on. I've been telling CMake to use just 'g++' which is at version GCC 6.4.0, but I have the feeling that compute++ is using /usr/bin/c++ because I keep getting the following error:

``error: no member named 'is_trivially_copyable' in namespace 'std'`` which is apparently due to GCC versions older then 5 not fully implementing the C++11 standard. 

I've ran CMake using:
```
cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CC_COMPILER=gcc  -DComputeCpp_DIR=~/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/
```

I've also tried to use compute++ without CMake. For example on the simple-vector-add sample code I ran
```
compute++ -sycl simple-vector-add.cpp
```
which successfully produces a simple-vector-add.sycl file. 
However when I try the second step of the compilation process:
```
compute++ -include simple-vector-add.sycl simple-vector-add.cpp -o simple-vector-add
```
I again get the ``error: no member named 'is_trivially_copyable' in namespace 'std' `` error.

Am I doing something wrong here? Or is there another way to tell compute++ which compiler it should use?

**Comment by DuncanMcBain** [comment]
You can invoke `compute++` with the `-v` flag and it will output where it is looking for system headers - it looks like it is finding the wrong one. Normally Clang just uses the most recent version of `libstdc++` it can find so it's strange that on a system with both GCC 4 and 6 it can't find the 6 headers - unless they're in some nonstandard location. That same flag works with GCC, so you can query where it's looking too.

That being said, it is strange that in your non-CMake build the first step (generating the device code) works but the second step *doesn't*. You can actually use whatever host compiler you please for the second step, so you should be able to run something like `g++ -include simple-vector-add.sycl simple-vector-add.cpp -o simple-vector-add`. In theory, the actual command line run by CMake shouldn't look too different to this (you can see these either with `make VERBOSE=1` or `ninja -v` when building a target). When the CMake build fails, which step doesn't find the right header? It will tell you which target failed; if it ends in `.sycl` it's the device code, `.o` means the host side of the compilation failed.

An alternative to all that is to do a sort-of pretend cross-compile, where you just use a standalone GCC tarball. That is how we do cross-compiling to ARM (for example) but it would work just as well with an ordinary x86 release of GCC. The benefit of this approach is that you'd know exactly what you're using to build.

Let me know if you'd like to go down that route, we have some instructions kicking around on the website.

**Comment by benvanwerkhoven** [comment]
Wow thanks for the very quick reply! I managed to compile the code now in the second step with the following command:
```
g++ -v -include simple-vector-add.sycl simple-vector-add.cpp -lComputeCpp -L$HOME/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/lib/ -o simple-vector-add
```

I don't know why, but -v reveals that compute++ indeed gets into the headers of GCC 4.8.5 on my system. This does not happen when using g++ directly.

I can't use the one step compilation with this setup, but this should get me going for now at least. Thanks!

**Comment by DuncanMcBain** [comment]
What happens if you add `-v` to the step where you generate the device code (i.e. the `-sycl` step)?

**Comment by benvanwerkhoven** [comment]
I get the following:

```
$ compute++ -v -sycl  simple-vector-add.cpp
Codeplay ComputeCpp - CE 2.0.0 Device Compiler - clang version 8.0.0  (based on LLVM 8.0.0svn)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/bwn200/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Selected GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found CUDA installation: /cm/shared/apps/cuda91/toolkit/9.1.85, version 9.1
 "/home/bwn200/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/bin/compute++" -cc1 -triple x86_64-unknown-linux-gnu -aux-triple spir64-unknown-unknown -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name simple-vector-add.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu x86-64 -dwarf-column-info -debugger-tuning=gdb -v -resource-dir /home/bwn200/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/lib/clang/8.0.0 -I/cm/shared/package/nccl/cuda90/nccl_2.1.2-1+cuda9.0_x86_64/include -I/cm/shared/package/cuDNN/cuda10.0/7.6.4/cudnn/cuda/include -I/cm/shared/apps/openmpi/cuda/64/3.1.1/include -I/cm/shared/apps/cuda91/sdk/9.1.85/common/inc -I/cm/shared/apps/cuda91/toolkit/9.1.85/targets/x86_64-linux/include -I/cm/shared/apps/hpcx/2.0.0/ucx/include -I/cm/shared/apps/hpcx/2.0.0/sharp/include -I/cm/shared/apps/hpcx/2.0.0/mxm/include -I/cm/shared/apps/hpcx/2.0.0/hcoll/include -I/home/bwn200/cub/ -I/cm/shared/apps/cuda10.0/sdk/10.0.130/common/inc -I/cm/shared/apps/cuda10.0/toolkit/10.0.130/targets/x86_64-linux/include -I/cm/shared/apps/slurm/17.02.2/include -I/home/bwn200/alessio/include -I/home/bwn200/cupy/build/lib.linux-x86_64-3.5/cupy/core/include -I/home/bwn200/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/include -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5 -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/x86_64-redhat-linux -internal-isystem /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/backward -internal-isystem /usr/local/include -internal-isystem /home/bwn200/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/lib/clang/8.0.0/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++11 -fdeprecated-macro -fdebug-compilation-dir /home/bwn200/computecpp-sdk/samples -ferror-limit 19 -fmessage-length 169 -fobjc-runtime=gcc -fcxx-exceptions -fexceptions -sycl -Rsycl-serial-memop -Rsycl-kernel-naming -sycl-ih-md /tmp/simple-vector-add-1018e2.mdsycl -fno-sycl-emit-ih -fdiagnostics-show-option -fcolor-diagnostics -o /tmp/simple-vector-add-f8c00a.o -x c++ simple-vector-add.cpp
clang -cc1 version 8.0.0 based upon LLVM 8.0.0svn default target x86_64-unknown-linux-gnu
ignoring nonexistent directory "/cm/shared/apps/cuda91/sdk/9.1.85/common/inc"
ignoring nonexistent directory "/include"
#include "..." search starts here:
#include <...> search starts here:
 /cm/shared/package/nccl/cuda90/nccl_2.1.2-1+cuda9.0_x86_64/include
 /cm/shared/package/cuDNN/cuda10.0/7.6.4/cudnn/cuda/include
 /cm/shared/apps/openmpi/cuda/64/3.1.1/include
 /cm/shared/apps/cuda91/toolkit/9.1.85/targets/x86_64-linux/include
 /cm/shared/apps/hpcx/2.0.0/ucx/include
 /cm/shared/apps/hpcx/2.0.0/sharp/include
 /cm/shared/apps/hpcx/2.0.0/mxm/include
 /cm/shared/apps/hpcx/2.0.0/hcoll/include
 /home/bwn200/cub
 /cm/shared/apps/cuda10.0/sdk/10.0.130/common/inc
 /cm/shared/apps/cuda10.0/toolkit/10.0.130/targets/x86_64-linux/include
 /cm/shared/apps/slurm/17.02.2/include
 /home/bwn200/alessio/include
 /home/bwn200/cupy/build/lib.linux-x86_64-3.5/cupy/core/include
 /home/bwn200/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/include
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/x86_64-redhat-linux
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/backward
 /usr/local/include
 /home/bwn200/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/lib/clang/8.0.0/include
 /usr/include
End of search list.
remark: [Computecpp:CC0027]: Some memcpy/memset intrinsics added by the llvm optimizer were replaced by serial functions. This is a workaround for OpenCL drivers that do
      not support those intrinsics. This may impact performance, consider using -no-serial-memop. [-Rsycl-serial-memop]
 "/home/bwn200/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/bin/spirv-ll-tool" --binary --api OpenCL --enable-all --address-bits 64 --output /tmp/simple-vector-add-6f694d.bc /tmp/simple-vector-add-f8c00a.o
/home/bwn200/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/bin/spirv-ll-tool: /lib64/libtinfo.so.5: no version information available (required by /home/bwn200/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/bin/spirv-ll-tool)
 "/home/bwn200/ComputeCpp-CE-2.0.0-x86_64-linux-gnu/bin/sycl-bundler" -i /tmp/simple-vector-add-1018e2.mdsycl,/tmp/simple-vector-add-6f694d.bc,spir64 -o simple-vector-add.sycl
```

So somehow the headers from this location are included:
```
 /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5
```

Whereas g++ -v uses:
```
/cm/shared/package/gcc/6.4.0/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../include/c++/6.4.0
```
To search for headers.

**Comment by DuncanMcBain** [comment]
Ah, and I think actually the `std::is_trivially_copyable` code doesn't turn up in the device variants of the ComputeCpp headers. Mystery (somewhat) solved! You'll have to somehow tell `compute++` where to find the headers. If the stuff in `/cm/shared` is laid out in a relatively standard way, you might be able to use the flag `--gcc-toolchain` to point it in the right direction. Otherwise, you can set the paths using `-isystem`, though this is fiddly to do by hand. I imagine you'd also need `nostdinc` to stop `compute++` using the directories it's already found.

**Comment by DuncanMcBain** [comment]
Hi @benvanwerkhoven, did either of these ideas end up working for you? Sorry for not being in contact earlier, I should have followed up to see if we could help you further!

**Comment by rodburns** [comment]
Since this has been dormant for quite a long time I will close this but feel free to re-open it or raise a new issue if you need further help. Thanks.
