### ISSUE TITLE
error: no matching function for call to 'clCreateProgramWithSource'

### ISSUE THREAD

**Issue by AD2605** [codeplaysoftware/computecpp-sdk#245]
Hello all, 
I am building and installing ComputeCpp-SDK from source and during the make command I get the error - `/home/atharva/computecpp-sdk/samples/opencl-c-interop.cpp:105:28: error: no matching function for call to 'clCreateProgramWithSource'
    cl_program clProgram = clCreateProgramWithSource(
`
I am building computecpp-SDK in the following manner -
```
cmake .. -D ComputeCpp_DIR=/home/atharva/computecpp/computecpp -D OpenCL_INCLUDE_DIRS=/usr/local/cuda/include/ -D OpenCL_LIBRARIES=/usr/local/cuda/lib64/ -D COMPUTECPP_BITCODE=ptx64
```
followed by 
`make -j12`
What could I do to solve this ?
EDIT - I just ran `make clear and make -j12`, the above issue goes away but the build stops are 57% after building vptr and gaussian blur, the last message on terminal being - `*** [Makefile:141: all] Error 2` and the issue appears again after building with just one core at 72%/

**Comment by mcleary** [comment]
Could you provide the full build log please? It seems you're using the CUDA OpenCL headers and the `clCreateProgramWithSource` doesn't have the expected signature. 

Could you also please try the OpenCL headers from the [official Khronos repository](https://github.com/KhronosGroup/OpenCL-Headers)?

**Comment by mcleary** [comment]
On another note, the `OpenCL_LIBRARY` option should point to `libOpenCL.so`, so you command line should actually be

```
cmake .. -DComputeCpp_DIR=/home/atharva/computecpp/computecpp -DOpenCL_INCLUDE_DIRS=/usr/local/cuda/include/ -D OpenCL_LIBRARIES=/usr/local/cuda/lib64/libOpenCL.so -D COMPUTECPP_BITCODE=ptx64
```

**Comment by AD2605** [comment]
Hello @mcleary , Thank you for the quick reply, actually in the CMake file, I had set the CXX standard as 17, when I reverted back to 14 it built perfectly. I ran `./samples/simple-vector-add` and got the output `The results were correct`. Also just giving path to lib and specifically the openCl.so file works too. 
Maybe cuda OpenCL headers do not have cxx 17 support ?

**Comment by mcleary** [comment]
> Maybe cuda OpenCL headers do not have cxx 17 support ?

Could be. I don't have the headers in my machine to verify but I always use the official khronos OpenCL headers to avoid these problems since OpenCL support in nvidia is not amazing. 

I will close this issue then. If you have more problems feel free to reopen it.

**Comment by AD2605** [comment]
Sure thanks a lot for your help...
