### ISSUE TITLE
Enabling __CUDACC__ is a bold move

### ISSUE THREAD

**Issue by MathiasMagnus** [codeplaysoftware/computecpp-sdk#246]
I don't quite undertand the [change](https://github.com/codeplaysoftware/computecpp-sdk/commit/8114ff0c48383a405ff043186e24470afae7ef3b#diff-59f994a125be3e4994fd4323a7d9dca6R41) in `ComputeCppCompilerChecks.cmake `.

MSVC STL tries to play nice nvcc and disables the STL version requirement checks when it detects being compiled with nvcc. But computecpp pretending to be nvcc is calling for trouble. That means that on Windows, ComputeCpp will likely enable CUDA code paths in projects which are designed to have a CUDA back-end.

@mcleary could you elaborate on what was the reason to broaden the scope of the remedy to simply disabling the version check to pretending to be nvcc altogether?

**Comment by mcleary** [comment]
I understand your concern and this is something we are monitoring closely in case it backfires. 

The main reason for the change you mentioned is the fact that MSVC 14.27 expects clang 10 to be used. compute++ is based on clang 8, so until we can upgrade it this define will be required to use the the latest iteration of Visual Studio. We could ask our users to downgrade to MSVC 14.26 and that still works but it is a real hassle to make work with it in CMake based projects.

The main driver for this change was this piece of code:

```c++
// FUNCTION TEMPLATE _Bit_cast
template <class _To, class _From,
    enable_if_t<conjunction_v<bool_constant<sizeof(_To) == sizeof(_From)>, is_trivially_copyable<_To>,
                    is_trivially_copyable<_From>>,
        int> = 0>
#ifdef __CUDACC__
_NODISCARD _To _Bit_cast(const _From& _Val) noexcept {
    _To _To_obj; // assumes default-init
    _CSTD memcpy(_STD addressof(_To_obj), _STD addressof(_Val), sizeof(_To));
    return _To_obj;
}
#else // ^^^ workaround ^^^ / vvv no workaround vvv
_NODISCARD constexpr _To _Bit_cast(const _From& _Val) noexcept {
    return __builtin_bit_cast(_To, _Val);
}
#endif // ^^^ no workaround ^^^
```

`compute++` complains that 

```
error G959205E0: '_To' does not refer to a value
      return __builtin_bit_cast(_To, _Val);
                                ^
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\xutility:51:17: note: declared here
  template <class _To, class _From,
```

Hope this clarifies why the change was made. Despite that, our internal testing has passed so it was decided this would not be a problem for the time being. When we have a new version of clang we can remove this from this sdk.

**Comment by MathiasMagnus** [comment]
@mcleary I see why it was introduced. Because this is purely an STL issue I would suggest opening a PR to the [MSVC STL](https://github.com/microsoft/STL) repo and actually upstream changes required to detect any type of device compiler with a different set of builtins / front-end assumptions. ComputeCpp defines it's own macro that can be used instead of __CUDACC__ and MSVC's STL can be taught to trigger on those too.

I'll let you decide when to close this issue.

**Comment by psalz** [comment]
> That means that on Windows, ComputeCpp will likely enable CUDA code paths in projects which are designed to have a CUDA back-end.

Yup, I've now seen in two separate instances how things break spectacularly as soon as one attempts to include a template library that has dedicated CUDA support. For example various Boost libraries and Eigen3.
