### ISSUE TITLE
is_accessor trait requires exactly 5 template arguments

### ISSUE THREAD

**Issue by alexbatashev** [codeplaysoftware/computecpp-sdk#247]
`is_accessor` type trait requires that SYCL implementation provides a `cl::sycl::accessor` type with exactly 5 template arguments:
https://github.com/codeplaysoftware/computecpp-sdk/blob/8114ff0c48383a405ff043186e24470afae7ef3b/include/ivka/ivka.hpp#L45-L55

At the same time, implementations may extend SYCL specification. For example, DPC++ provides ability to specify compile-time-constant properties for accessors: [SYCL_ONEAPI_accessor_properties](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/accessor_properties/SYCL_ONEAPI_accessor_properties.asciidoc). This breaks samples from this repository.

As an alternative, I suggest changing implementation, so that it checks if `T` is a `sycl::accessor` template, without checking its template arguments.

**Comment by mcleary** [comment]
That is a good suggestion. Would you be able to provide a pull request?

**Comment by alexbatashev** [comment]
@mcleary sure

**Comment by alexbatashev** [comment]
I couldn't quickly find a portable way to match any template parameters. C++ definitely lacks some kind of `auto...` parameter pack that expands to list of type and non-type parameters. But, there's a C++11 way to allow `cl::sycl::accessor` to have any default parameter after spec-defined parameters, which fixes these samples compilation with DPC++. So, here's a pull request: https://github.com/codeplaysoftware/computecpp-sdk/pull/248

**Comment by mcleary** [comment]
Closing this since #248 was merged
