### ISSUE TITLE
atomic add  for double

### ISSUE THREAD

**Issue by mtxuhao** [codeplaysoftware/computecpp-sdk#263]
now computecpp not support float&double atomic add ,
Will it be supported in the future.because float &double atomic op is common in hpc application

**Comment by rodburns** [comment]
Thanks for raising this question. ComputeCpp is implementing support for SYCL 2020 and part of this specification are float and double atomic support. So this will be implemented in ComputeCpp at some point in the future. The implementation of this support may depend on the hardware so in some cases it may be emulated. 
Do you have a specific hardware target in mind?
