### ISSUE TITLE
about __SYCL_DEVICE_ONLY__  macro

### ISSUE THREAD

**Issue by mtxuhao** [codeplaysoftware/computecpp-sdk#267]
i want to implement  a function by device buildin fun.but may __SYCL_DEVICE_ONLY__   not defined ，so it not work .
i need your help  ,thanks very much
i call device_buildin fun inter parallel_for ensure compute++ work and compile sycl code
err is followed :
error: ‘helper_asp’ is not a member of ‘cl::sycl::detail’

i want to call  this function:
inline sycl::cl_long atom_cmpxchg(
    detail::helper_ptr<detail::helper_asp::asp_global,
                       COMPUTECPP_CL_ASP_GLOBAL volatile sycl::cl_long*>
        p,
    sycl::cl_long cmp, sycl::cl_long val) noexcept {
  return sycl::cl_long(::_Z12atom_cmpxchgPU3AS1Vlll(p, cmp, val));
}

**Comment by rodburns** [comment]
Can you provide a small repro example or similar to help us understand your problem better please?
Thanks, Rod.
