### ISSUE TITLE
Missing ComputeCpp.props error

### ISSUE THREAD

**Issue by GravermanDev** [codeplaysoftware/computecpp-sdk#288]
Hello, I wanted to use this SYCL implementation but I have problem with running the example code. The error I get goes as follows:
`MSB4019	The imported project "D:\VC Community 2019\MSBuild\Microsoft\VC\v160\BuildCustomizations\ComputeCpp.props" was not found. Confirm that the expression in the Import declaration "D:\VC Community 2019\MSBuild\Microsoft\VC\v160\\BuildCustomizations\ComputeCpp.props" is correct, and that the file exists on disk.`

I installed computecpp using [this](https://youtu.be/lTDD5dWGEE0) tutorial. I don't know if I did something wrong or if this is a bug
but please help me

Thank you

**Comment by GravermanDev** [comment]
so I found the problem, I had these files in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations`

**Comment by DuncanMcBain** [comment]
Hi @GravermanDev, did you have to change the import declaration to point to the actual location of the file? Is this something we need to change in our downloadable package? We more or less just use the basic CMake configuration to make it work.

**Comment by GravermanDev** [comment]
I copied the file and placed in it's place. The folders that I found were created by the installer. I store all my applications on D drive instead of on C:\ProgramFiles and the download package just had to put this file somewhere

**Comment by DuncanMcBain** [comment]
OK, thank you for the information. I'm glad you were able to get it working!
