### ISSUE TITLE
Exception when running VS example code

### ISSUE THREAD

**Issue by fiewosjfiowejfiewjfiw** [codeplaysoftware/computecpp-sdk#289]
Hello, I want to run the test project on SYCL (the one that just adds two arrays of size 1024) but I get an exception when submit to the queue
` queue myQueue(mySelector);`
The exception throws this message:
`Unhandled exception at 0x00007FF98F704FD9 in Evolution Engine.exe: Microsoft C++ exception: std::bad_array_new_length at memory location 0x000000A8626FBDE0.`

I checked with VS debugger and the three arrays are at locations;
0x000000a8626fc050
0x000000a8626fd070
0x000000a8626fe090 

here is the full code:
https://pastebin.com/xZV7n2Ah

I use SYCL 1.2.1 revision 3 and my device is supported by ComputeCpp

**Comment by DuncanMcBain** [comment]
Hi @fiewosjfiowejfiewjfiw, thanks for the report. The code mostly looks correct to me. Would it be possible for you to run in a debugger to see precisely where the exception is being thrown from (i.e. line of code)?

**Comment by fiewosjfiowejfiewjfiw** [comment]
for some reason this has changed since I wrote the issue. Right now it throws exception at
``cgh.parallel_for<class vector_add>(`` so line 51. It also opens a file program.h at line ``return program(create_program_for_kernel_impl(
        kernelName.c_str(), binInfo.data, binInfo.data_size,
        binInfo.used_extensions, c.get_impl(), binInfo.target)``

**Comment by DuncanMcBain** [comment]
That makes slightly more sense. How did you compile this code? It looks like there might somehow be a problem with the compiled kernel, but I'm not sure how.

**Comment by fiewosjfiowejfiewjfiw** [comment]
I'm compiling this using vs plugin that I set up following [this ](https://www.youtube.com/watch?v=lTDD5dWGEE0&t) tutorial

**Comment by DuncanMcBain** [comment]
I am not familiar with that video. Do you have any warnings when you compile the sample? Have you tried using the CMake distributed with this repo instead of the plugin?
