### ISSUE TITLE
MSVC new project not running

### ISSUE THREAD

**Issue by trsh** [codeplaysoftware/computecpp-sdk#292]
I closely fallowed this tutorial and on building it reported missing OpenCL headers. So I added additional include directory "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.0\include" which has CL headers. After that it built fine, but on in runtime I got this:

```
Error: [ComputeCpp:RT0100] Failed to build program (<Build log for program 000001F11E8A7990 (size: 65) error   : Binary format for key='0', ident='' is not recognized


>


 )
```

Specs:

Windows 11 x64
Intel i5 CPU, RTX 3060 GPU
Visual Studio 2019 (up to date)
ComputeCpp-CE-2.11.0-x86_64-windows-msvc
Cuda v12.0 with openCL

**Comment by DuncanMcBain** [comment]
Hi @trsh,

that error normally means that you are outputting the wrong binary format for the nvidia driver. You can likely fix this by changing the `COMPUTECPP_BITCODE` variable in CMake to `ptx64`. That said, this is likely not going to work for other reasons, and we'd now strongly recommend that you try Intel's dpc++ compiler for targeting SYCL code on nvidia GPUs.

I hope this helps,
Duncan.
