### ISSUE TITLE
Custom OpenCL include dirs is not passed to the device compiler

### ISSUE THREAD

**Issue by ppadrons** [codeplaysoftware/computecpp-sdk#3]
When using the following line with a custom OpenCL include dir:

`cmake .. -DCOMPUTECPP_PACKAGE_ROOT_DIR=$HOME/ComputeCPP/ComputeCpp-CE-0.1-Linux -DOpenCL_INCLUDE_DIR=/usr/local/include`

The OpenCL include dir path is not used on the device compiler, as you can see in the following make output produced by cmake:

`cd $HOME/ComputeCPP/computecpp-sdk/samples/build/images && $HOME/ComputeCPP/ComputeCpp-CE-0.1-Linux/bin/compute++ -O2 -mllvm -inline-threshold=1000 -sycl -intelspirmetadata -emit-llvm -isystem $HOME/ComputeCPP/ComputeCpp-CE-0.1-Linux/include/ -I$HOME/ComputeCPP/ComputeCpp-CE-0.1-Linux/include -I$HOME/ComputeCPP/ComputeCpp-CE-0.1-Linux/include -o $HOME/ComputeCPP/computecpp-sdk/samples/build/images/images.cpp.sycl -c $HOME/ComputeCPP/computecpp-sdk/samples/images/images.cpp`

**Comment by DuncanMcBain** [comment]
Hi, thanks for reporting this. It looks like we might not be setting the OpenCL include directory properly at all. I'll try to come up with a fix shortly.

**Comment by DuncanMcBain** [comment]
Hi,
can you try this branch please? It's a one-line fix and should add the custom OpenCL directory to the command lines of both the host and device compilers.

https://github.com/codeplaysoftware/computecpp-sdk/tree/issue/3

**Comment by ppadrons** [comment]
Works flawlessly :)

**Comment by DuncanMcBain** [comment]
OK great, I will merge this into master. Thanks!
