### ISSUE TITLE
CMAKE_INSTALL_DIR is unused

### ISSUE THREAD

**Issue by 7thsanctum** [codeplaysoftware/computecpp-sdk#37]
The readme mentions `CMAKE_INSTALL_DIR `. When this is set I get a warning saying it is unused by the project. I suspect that the correct var is `CMAKE_INSTALL_PREFIX`. 

Alongside this, when I set `CMAKE_INSTALL_PREFIX` there is no install target. 

This is with cmake version 3.5.1 and ninja version 1.5.1.

**Comment by DuncanMcBain** [comment]
Fixed in 6829feb36c8eee1a795f521dd5ef861eb8a53f6b!
