### ISSUE TITLE
Copyright year in FindComputeCpp.cmake

### ISSUE THREAD

**Issue by tremmelg** [codeplaysoftware/computecpp-sdk#74]
Copyright year in FindComputeCpp.cmake says 2016.

**Comment by DuncanMcBain** [comment]
As I understand it, the copyright notice is there to assert the year in which the file was first published, and as such should continue to say 2016.

**Comment by tremmelg** [comment]
@Ruyk

**Comment by Ruyk** [comment]
We should use a range of years, like we do in all other places. In this case, 2016 - 2017 (soon 2018). This helps identify how old is the file and when was updated, in case it is copied around outside of git (which will particularly happen in this case).

**Comment by rodburns** [comment]
I've changed this but seems all the files in the project need updating.
