### ISSUE TITLE
Strange workaround in FindComputeCpp.cmake

### ISSUE THREAD

**Issue by Ruyk** [codeplaysoftware/computecpp-sdk#79]
The following piece of code from the FindComputeCpp.cmake looks weird. The force include flags, used in properties later on, should be lists, and not strings. However, the comment seems to indicate the Visual Studio generator requires strings, and not lists. This could be a bug on the CMake generator,

```
    # NOTE: The Visual Studio generators parse compile flags differently,
    # hence the different argument syntax
    if(CMAKE_GENERATOR MATCHES "Visual Studio")
      set(forceIncludeFlags "/FI\"${includedFile}\" /TP")
    else()
      set(forceIncludeFlags /FI ${includedFile} /TP)
    endif()   
```

**Comment by DuncanMcBain** [comment]
This was fixed in #149
