### ISSUE TITLE
Unable to link to standard libraries?

### ISSUE THREAD

**Issue by domantasjurkus** [codeplaysoftware/computecpp-sdk#86]
Hello, I am having issues adding SYCL to my target application. My situation is that I need to link to standard libraries, however using `add_sycl_to_target` seems to give me an error when I try to use `target_link_libraries`.

```
# For testing
set(common_libraries stdc++ pthread)
add_executable(reduction ${CMAKE_CURRENT_SOURCE_DIR}/reduction.cpp)

target_link_libraries(reduction ${common_libraries})
add_sycl_to_target(reduction ${CMAKE_CURRENT_BINARY_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/reduction.cpp)
```

The error:
```
CMake Error at /home/dom/computecpp-sdk/cmake/Modules/FindComputeCpp.cmake:366 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "reduction".  All uses of target_link_libraries with a target
  must be either all-keyword or all-plain.
```

Now after a bit of googling I understand that it's a generic CMake error involving dependencies as mix of keywords and plaintext, but I still cannot seem to figure out how to resolve the issue. Any advice is appreciated.

**Comment by DuncanMcBain** [comment]
What CMake version are you using? Have you tried specifying the PUBLIC or PRIVATE keywords when linking against these libs?

**Comment by domantasjurkus** [comment]
`cmake version 3.5.1`. I guess I can throw in the entire CMake file for completeness:

```
cmake_minimum_required(VERSION 3.2.2)
project(Tutorial)

set(CMAKE_CXX_STANDARD 11)

include_directories("${PROJECT_BINARY_DIR}")

set(COMPUTECPP_PACKAGE_ROOT_DIR /home/dom/computecpp-ce-0.5.1)
set(COMPUTECPP_INCLUDE_DIRECTORY /home/dom/computecpp-ce-0.5.1/include)
set(SYCL_PARALLEL_STL_INCLUDE_DIRECTORY /home/dom/sycl_parallel_stl/include)

set(CMAKE_MODULE_PATH /home/dom/computecpp-sdk/cmake/Modules/)
include(FindComputeCpp)

include_directories(${COMPUTECPP_INCLUDE_DIRECTORY})
include_directories(${SYCL_PARALLEL_STL_INCLUDE_DIRECTORY})

add_definitions(-DSYCL_PSTL_USE_OLD_ALGO)
set(COMPUTECPP_DEVICE_COMPILER_FLAGS "${COMPUTECPP_DEVICE_COMPILER_FLAGS} -DSYCL_PSTL_USE_OLD_ALGO")

# For testings
set(common_libraries stdc++ pthread)
add_executable(reduction ${CMAKE_CURRENT_SOURCE_DIR}/reduction.cpp)

target_link_libraries(reduction ${common_libraries})
add_sycl_to_target(reduction ${CMAKE_CURRENT_BINARY_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/reduction.cpp)
```

**Comment by domantasjurkus** [comment]
This seems to work, hooray:
```
target_link_libraries(reduction PRIVATE ${common_libraries})
```

**Comment by domantasjurkus** [comment]
Uh, I'm having some more trouble, `compute++` cannot seem to find my source files.

The previous example was more of a standalone dummy to see how to build SYCL projects with CMake. Below is a snippet from my actual application file: I want to use SyclParallelSTL for all `STL_FILES`:

```
...
# ----------------- SYCL/STL VERSION -----------------
set(COMPUTECPP_PACKAGE_ROOT_DIR /home/dom/computecpp-ce-0.5.1)
set(COMPUTECPP_INCLUDE_DIRECTORY /home/dom/computecpp-ce-0.5.1/include)
set(SYCL_PARALLEL_STL_INCLUDE_DIRECTORY /home/dom/sycl_parallel_stl/include)

set(CMAKE_MODULE_PATH /home/dom/computecpp-sdk/cmake/Modules/)
include(FindComputeCpp)

include_directories(${COMPUTECPP_INCLUDE_DIRECTORY})
include_directories(${SYCL_PARALLEL_STL_INCLUDE_DIRECTORY})

add_definitions(-DSYCL_PSTL_USE_OLD_ALGO)
set(COMPUTECPP_DEVICE_COMPILER_FLAGS "${COMPUTECPP_DEVICE_COMPILER_FLAGS} -DSYCL_PSTL_USE_OLD_ALGO")

set(STL_FILES src/stl/kernels.cpp
            src/stl/preprocess.cpp
            src/stl/track.cpp
            src/stl/integrate.cpp
            src/stl/raycast.cpp
            src/stl/raycasting.cpp
            src/stl/render.cpp)

add_library(${appname}-stl ${STL_FILES})
target_link_libraries(${appname}-stl PRIVATE ${common_libraries})

add_sycl_to_target(${appname}-stl ${CMAKE_CURRENT_BINARY_DIR} ${STL_FILES})
add_version(${appname} stl "" "")
...
```

Output from CMake (Looks like a simple directory issue..?):
```
dom@dom:~/gu/Project/slambench/build$ make
...
[ 30%] Building ComputeCpp integration header file /home/dom/gu/Project/slambench/build/kfusion/raycast.cpp.sycl
compute++: error: no such file or directory: 'src/stl/raycast.cpp'
compute++: error: no input files
...
```

**Comment by DuncanMcBain** [comment]
You shouldn't need to do stuff with the ComputeCpp includes directly, the modules *should* handle that. If it's not working, let me know. We also have a variable `COMPUTECPP_USER_FLAGS" which is appended to the command line of compute++, to enable users to pass flags much like you're doing now.

We might handle relative paths incorrectly, it's definitely possible. I can't investigate now but might be able to have a look tomorrow. If you were able to show me what the equivalent command line for the host is (i.e. how to build raycast.o), I might get some insight as to what is going wrong.

**Comment by domantasjurkus** [comment]
I am not sure how to show you the equivalent command line since the build process is a bit complex for my expertise. Basically raycast.o is not built, the functions in raycast.cpp are used as a library for building several variations of executables that use the STL.

I've pushed my attempt so far into a separate branch. You should be able to see the full project configuration:
https://github.com/domantasjurkus/slambench/tree/add_sycl

**Comment by DuncanMcBain** [comment]
The dry-run option of make will show you what commands are being run - you can do `make -n` to show this. Quite useful for debugging problems like this!

Anyway, I think I've kind of tracked down what's happening. Broadly, CMake has a better concept of what a source file is than we can provide in FindComputeCpp.cmake, in that the commands CMake produces for the host compiler are perfectly well able to make changes to enable use of relative paths, for example. The fragility (or, you know, bug) you seem to have found in our CMake is that in all the stuff we've written, we use something like:
```cmake
add_sycl_to_target(
  ${SOURCE_NAME}
  ${CMAKE_CURRENT_BINARY_DIR}
  ${CMAKE_CURRENT_SOURCE_DIR}/${SOURCE_NAME}.cpp
)
```
This sends the whole path to the file to our device compiler, but if you don't do that then it gets a relative path that ends up not being correct. For the moment, can you try adding `${CMAKE_CURRENT_SOURCE_DIR}` to your CMake code to see if that fixes it? We should improve this, but I haven't really thought about how best to do that. Thanks!

**Comment by domantasjurkus** [comment]
Prefixing each source file with `${CMAKE_CURRENT_SOURCE_DIR}` worked.

**Comment by DuncanMcBain** [comment]
Great, glad to hear it! I will make a task for us to fix this in the future, thanks!
