### ISSUE TITLE
Building samples error

### ISSUE THREAD

**Issue by Wheest** [codeplaysoftware/computecpp-sdk#88]
Have been following [the guide](https://developer.codeplay.com/computecppce/latest/getting-started-guide) on building the samples, and running `cmake` works fine.  However, `make` fails with the following output
````
[  2%] Building ComputeCpp integration header file /hdd/repos/computecpp-sdk/build/samples/simple-local-barrier/simple-local-barrier.cpp.sycl
compute++: error: no such file or directory: 'Error:'
compute++: error: no such file or directory: 'Fail'
compute++: error: no such file or directory: 'to'
compute++: error: no such file or directory: 'load'
compute++: error: no such file or directory: 'fglrx'
compute++: error: no such file or directory: 'kernel'
compute++: error: no such file or directory: 'module!'
compute++: error: no input files
make[2]: *** [samples/simple-local-barrier/simple-local-barrier.cpp.sycl] Error 1
make[1]: *** [samples/simple-local-barrier/CMakeFiles/simple-local-barrier_simple-local-barrier.cpp_0_ih.dir/all] Error 2
make: *** [all] Error 2
````
Unsure what direction to head in, tried poking around removing and reinstalling fglrx via apt, to no avail.  Aid would be appreciated

**Comment by DuncanMcBain** [comment]
The reason you're seeing the error is because during the CMake configure process, we call a program called `computecpp_info` to get some information from about the system, including what compilation flags should be passed to the device compiler (it is done like this so that the CMake can be updated out-of-band with the ComputeCpp CE while still being guaranteed to work). However, because your drivers are somehow not working properly, when `computecpp_info` runs, the output is muddied with the error about loading the fglrx kernel module. I am not sure what information to offer for fixing that, as I don't know what hardware and software you have, but I can suggest a change that would perhaps allow you to build the SDK at the very least (though again, if you cannot even load the fglrx module, the samples are unlikely then to run even if built).

If you look at [FindComputeCpp.cmake:175](https://github.com/codeplaysoftware/computecpp-sdk/blob/master/cmake/Modules/FindComputeCpp.cmake#L175), you can see where the info tool is called from. I can tell you that the flags you would need are `-O2 -mllvm -inline-threshold=1000 -sycl -emit-llvm -intelspirmetadata` - adding those instead of executing the process should at least allow you to pass this point. I'm surprised that the previous check - obtaining the version number - didn't fail in the same way, though.

If you tell me more about what hardware and software you're running, I might be able to offer some suggestions, as I have a decent amount of experience installing and working with AMD's driver stack.

**Comment by Wheest** [comment]
Cheers, I notice now that `computecpp_info` is throwing those errors.  I must've assumed everything was fine when I saw my CPU device listed.

I'm running Ubuntu 14.04, and have followed most of the instructions in [Codeplay's TF guide](https://www.codeplay.com/portal/03-30-17-setting-up-tensorflow-with-opencl-using-sycl).

I have a R9 280x, which though picked up by `lspci -vnn | grep VGA -A 12`, only brought me problems when I attempted to install the fglrx packages listed in the guide.  When they are, `clinfo` fails with

````
modprobe: ERROR: ../libkmod/libkmod-module.c:809 kmod_module_insert_module() could not find module by name='fglrx'
modprobe: ERROR: could not insert 'fglrx': Function not implemented
Error: Fail to load fglrx kernel module!
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
*** Error in `clinfo': munmap_chunk(): invalid pointer: 0x00007f0b3b52911d ***
Aborted (core dumped)
````
Removing them, I spent a while seeing if the amdgpupro drivers might work instead, but that had broken dependencies that I haven't been able to follow through on yet.

I will look into the SDK build flags you recommend, but ultimately my goal is to use SYCL with Tensorflow, so I imagine that that would not permit that.

**Comment by DuncanMcBain** [comment]
Tensorflow doesn't actually use computecpp_info, so that wouldn't be a problem. However, I'm reasonably certain that as soon as you try to run some code, you'll just see the same error except from the sample code instead.

@lukeiwanski, can you remember the current drivers we suggest to people wanting to use AMD on Ubuntu?

**Comment by lukeiwanski** [comment]
Ubuntu 14.04 is EOL and the drivers setup is getting harder by day.. 
I did write a blog post a while ago ( http://deep-beta.co.uk/setting-up-tensorflow-with-opencl-using-sycl/ ) that describes on how to set up TF on Ubuntu 14.04

Essentially you need to downgrade your kernel to 3.19.
You can check your current kernel version by running 
`$ uname -a`

after that you can get fglx drivers from AMD website 

```$ sudo apt-get install ocl-icd-opencl-dev opencl-headers
$ wget --referer=http://support.amd.com https://www2.ati.com/drivers/linux/fglrx_15.302-0ubuntu1_amd64_ub_14.01.deb
$ wget --referer=http://support.amd.com https://www2.ati.com/drivers/linux/fglrx-core_15.302-0ubuntu1_amd64_ub_14.01.deb
$ sudo dpkg -i fglrx-core_15.302-0ubuntu1_amd64_ub_14.01.deb fglrx_15.302-0ubuntu1_amd64_ub_14.01.deb
$ sudo adduser $(whoami) video
$ sudo reboot
```
Let us know if that helps
Luke

**Comment by Wheest** [comment]
The recommendation to downgrade to kernel 3.19 worked.  I actually followed the step prior, but didn't check to see if it succeed.  Turns out I had 2 or 3 other kernels present that took precedent.  Removed, and `clinfo` now see my GPU (yass!).  Many thanks on that front.  

I was running Debian on my server before, but it seemed that Ubuntu was more driver friendly.  What OS/Hardware setup are you guys using in house nowadays?

Next error I am investigating
````
[  2%] Building ComputeCpp integration header file /hdd/repos/computecpp-sdk/build/samples/simple-local-barrier/simple-local-barrier.cpp.sycl
...
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ext/string_conversions.h:43:
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdio:120:11: error: no member named 'gets' in the global namespace
  using ::gets;
        ~~^
1 error generated.
...
````
Made sure that I'm definitely using cmake3.2.2, but will be trying different configurations over the next day

**Comment by DuncanMcBain** [comment]
That is an unusual error! It is possible that I've messed up and added some code that relies on a more recent version of GCC than 4.8, but I use 4.9 as my day-to-day so the changes should be fairly minimal... Could you print the full output from the failing step there, please? And do all samples fail with the same error? (If you don't know, you can convince make to continue building even when bits fail with the -k option.)

**Comment by Wheest** [comment]
The entirety of the output of `make` (sans -k flag):
````
[  2%] Building ComputeCpp integration header file /hdd/repos/computecpp-sdk/build/samples/simple-local-barrier/simple-local-barrier.cpp.sycl
In file included from /hdd/repos/computecpp-sdk/samples/simple-local-barrier/simple-local-barrier.cpp:28:
In file included from /usr/local/computecpp/include/CL/sycl.hpp:1:
In file included from /usr/local/computecpp/include/CL/../SYCL/sycl.hpp:20:
In file included from /usr/local/computecpp/include/SYCL/sycl_interface.h:21:
In file included from /usr/local/computecpp/include/SYCL/common.h:19:
In file included from /usr/local/computecpp/include/SYCL/predefines.h:456:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:55:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/tuple:39:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/array:38:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/stdexcept:39:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/string:52:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/bits/basic_string.h:2815:
In file included from /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/ext/string_conversions.h:43:
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/cstdio:120:11: error: no member named 'gets' in the global namespace
  using ::gets;
        ~~^
1 error generated.
make[2]: *** [samples/simple-local-barrier/simple-local-barrier.cpp.sycl] Error 1
make[1]: *** [samples/simple-local-barrier/CMakeFiles/simple-local-barrier_simple-local-barrier.cpp_0_ih.dir/all] Error 2
make: *** [all] Error 2
````
The same error appears when building all samples.  I will try with 4.9 to see if that makes a difference

**Comment by DuncanMcBain** [comment]
`ivka` is the "is valid kernel arg" sample, but it cannot be implemented with GCC < 5, unfortunately - however I'm pretty certain I added a check to [fail on GCC < 5 for ivka](https://github.com/codeplaysoftware/computecpp-sdk/blob/master/include/ivka/ivka.hpp#L35)! Glad that everything else is working, though.

I'm sure I've seen that gets() issue before... It doesn't look like we're doing anything particularly bizarre, I might check to see if adding the header that includes gets() to the sample fixes it.

What do you mean by your second argument? What flag do you need to change?

**Comment by Wheest** [comment]
I've no great allegiance to GCC versions, so I will see if `ivka` works when I upgrade.  Didn't get your check for fail when I tried earlier (as can be seen by the previous post, edit.  However, I checked again just now (after some reboots and other bits of unrelated system fiddling) and the GCC < 5 error is thrown now
````
/hdd/repos/computecpp-sdk/include/ivka/ivka.hpp:36:2: error: #error "is_valid_kernel_arg<T> requires GCC >= 5"
 #error "is_valid_kernel_arg<T> requires GCC >= 5"
````
Not sure what changed, but something must've.

My second edit was soon after the first, where I remembered that I could just use the `make -k` command and do without `ivka`.  My troubleshooting before I realized this had me looking at a forum post that suggested changing the std library at compile time.  Probably not the right thing to do, but I thought I'd leave that as a jumping off point if anyone in future wanted to pick up where I left off.

Am getting successful sample runs, attempting to familiar with the SYCL api and how it maps to OpenCL.  You will probably see me again as get more involved working with the Tensorflow setup, but for now thanks for the help

**Comment by DuncanMcBain** [comment]
OK, I understand now, thanks for clearing up! And I'm glad it's all working 👍 If you need other help about SYCL or our Tensorflow work, please don't hesitate to contact us :)
